// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FSK.Repository.Models;

public partial class Blog
{
    public int BlogId { get; set; }

    public int UserId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public int ElementId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ImageUrl { get; set; }

    public bool? IsActive { get; set; }

    public virtual Element Element { get; set; }
}