// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FSK.Repository.Models;

public partial class Interact
{
    public int InteractId { get; set; }

    public int AdsId { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual Advertisement Ads { get; set; }
}