// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FSK.Repository.Models;

public partial class Transaction
{
    public int TransactionId { get; set; }

    public int UserId { get; set; }

    public int AdsId { get; set; }

    public int PackageId { get; set; }

    public string TransactionDetail { get; set; }

    public int Duration { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime TransactionDate { get; set; }

    public decimal TotalPrice { get; set; }

    public bool? IsActive { get; set; }

    public virtual Advertisement Ads { get; set; }

    public virtual User User { get; set; }
}